<?php

namespace AppBundle\Repository;

/**
 * BattlePlaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattlePlaysRepository extends \Doctrine\ORM\EntityRepository
{
}
