<?php

namespace AppBundle\Repository;

/**
 * BattlePlayersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattlePlayersRepository extends \Doctrine\ORM\EntityRepository
{
}
