<?php

namespace AppBundle\Repository;

/**
 * BattleRoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleRoundRepository extends \Doctrine\ORM\EntityRepository
{
}
