<?php

namespace AppBundle\Repository;
use AppBundle\Entity\NBATeams;
use Doctrine\ORM\EntityManager;

/**
 * NBATeamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NBATeamsRepository extends \Doctrine\ORM\EntityRepository
{
}
