<?php

namespace AppBundle\Repository;

/**
 * NBATeamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NBATeamsRepository extends \Doctrine\ORM\EntityRepository
{
}
