<?php

namespace AppBundle\Repository;

/**
 * PlayTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayTypeRepository extends \Doctrine\ORM\EntityRepository
{
    const ONE_VERSUS_ONE_ID = 1;
    const TWO_VERSUS_TWO_ID = 2;
    const THREE_VERSUS_THREE_ID = 3;
    const ONE_VERSUS_ONE_TEMPL = '1v1.html.twig';
    const TWO_VERSUS_TWO_TEMPL = '2v2.html.twig';
    const THREE_VERSUS_THREE_TEMPL = '3v3.html.twig';

    public function getRandomPlayType($key)
    {
        $playTypes = $this->findAll();
        $playTypes[] = $this->find(self::TWO_VERSUS_TWO_ID);
        shuffle($playTypes);
        if (isset($playTypes[$key])) {
            return $playTypes[$key];
        }

        return null;
    }

    public function getAttackDefenseRound()
    {
        $rounds = [
            '1' => $this->getRandomPlayType(0),
            '3' => $this->getRandomPlayType(1),
        ];

        return $rounds;
    }

    public function getDefenseAttackRound()
    {
        $rounds = [
            '2' => $this->getRandomPlayType(2),
            '4' => $this->getRandomPlayType(3),
        ];

        return $rounds;
    }

    public function playTypeMapping()
    {
        $mapping = [
            self::ONE_VERSUS_ONE_ID => self::ONE_VERSUS_ONE_TEMPL,
            self::TWO_VERSUS_TWO_ID => self::TWO_VERSUS_TWO_TEMPL,
            self::THREE_VERSUS_THREE_ID => self::THREE_VERSUS_THREE_TEMPL,
        ];

        return $mapping;
    }
}
