<?php

namespace AppBundle\Repository;

/**
 * PublicTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
