<?php

namespace AppBundle\Repository;
use AppBundle\Entity\UsersPlayers;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping;
use Symfony\Component\Security\Csrf\TokenStorage\TokenStorageInterface;

/**
 * ShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository extends \Doctrine\ORM\EntityRepository
{
    public $userPlayers;
    public $user;

    public function __construct(ObjectManager $em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
        $this->userPlayers = $em->getRepository(UsersPlayers::class);
    }

    public function getShopPlayers($user)
    {
        $shopPlayers = $this->findBy([], ['id' => 'DESC'], 5);
        foreach ($shopPlayers as $shopPlayer) {
            $isInList = $this->userPlayers->findBy(['userId' => $user, 'playerId' => $shopPlayer->playerId]);
            $shopPlayer->isMyPlayer = empty($isInList);
        }

        return $shopPlayers;
    }
}
