<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Stadium;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;

/**
 * StadiumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StadiumRepository extends \Doctrine\ORM\EntityRepository
{
    protected $countStadium;

    public function __construct(EntityManager $em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
        $this->countStadium = count($this->findAll());

    }

    public function getRandomStadium()
    {
        $randomStadiumId = rand(1, $this->countStadium);
        $stadium = $this->find($randomStadiumId);
        if($stadium){

            return $stadium;
        }

        return null;
    }
}
