<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Trainer;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;

/**
 * TrainerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainerRepository extends \Doctrine\ORM\EntityRepository
{
    public $countTrainers;

    public function __construct(EntityManager $em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
        $this->countTrainers = count($this->findAll());
    }

    public function getRandomTrainer()
    {
        $randomTrainerId = rand(1, $this->countTrainers);
        $trainer = $this->find($randomTrainerId);
        if($trainer){

            return $trainer;
        }

        return null;
    }
}