<?php

namespace AppBundle\Repository;

/**
 * UserTopTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTopTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
