<?php

namespace AppBundle\Repository;

/**
 * UserBadgesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBadgesRepository extends \Doctrine\ORM\EntityRepository
{
}
