<?php

namespace AppBundle\Repository;

/**
 * UserDivisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDivisionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDivision($user) {

        $query = $this->createQueryBuilder("u")
            ->where('u.id = :id')
            ->setParameter('id', $user->getId());

        return $query;
    }
}
