<?php

namespace AppBundle\Repository;

/**
 * UserStadiumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStadiumRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkStadium($user, $stadium)
    {
        $userStadium = $this->findOneBy(['userId' => $user, 'stadiumId' => $stadium]);

        return empty($userStadium);
    }

    public function getMyStadium($user)
    {
        $myStadiums = $this->findBy(['userId' => $user]);

        return count($myStadiums);
    }
}
