<?php

namespace AppBundle\Repository;

/**
 * UserTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
