security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/dashboard, role: ROLE_USER }
        - { path: ^/team/new, role: ROLE_USER }
        - { path: ^/team/\d+/edit, role: ROLE_USER }
        - { path: ^/my-players, role: ROLE_USER }
        - { path: ^/pack, role: ROLE_USER }
        - { path: ^/dashboard, role: ROLE_USER }
        - { path: ^/battle/list, role: ROLE_USER }
        - { path: ^/battle, role: ROLE_USER }
        - { path: ^/profile, role: ROLE_USER }
        - { path: ^/profile/edit, role: ROLE_USER }
        - { path: ^/my-teams, role: ROLE_USER }
        - { path: ^/battle/\+d, role: ROLE_USER }
        - { path: ^/battle/\+d/play/\+d, role: ROLE_USER }